spring.jpa:
  database: mysql
  hibernate:
    dialect:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
  show-sql: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.219.195:3306/mybucketlist?useSSL=true&characterEncoding=UTF-8
    username: ${USER}
    password: ${PASSWORD}

jwt:
  secret-key: fastcampus_simple_sns_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000 # 24 * 60 * 60 * 60 * 1000


