spring.jpa:
  database: postgresql
  hibernate:
    dialect: org.hibernate.direct.PostgresSQLDialect
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
  show-sql: true

spring.datasource:
  hikari:
    maximum-pool-size: 4
  url: jdbc:postgresql://ec2-44-199-143-43.compute-1.amazonaws.com/ddct80i8jrlt1h
  username: grptnchqrdgtji
  password: 822a20a7c9965c0fcfcbe893b7a969904baf1009479205abf4095333a08a1027
  driver-class-name: org.postgresql.Driver

spring:
  sql:
    init:
      platform: postgres

jwt:
  secret-key: my-bucketlist-book_project-2023.secret_ket
  # 30 days
  token.expired-time-ms: 24 * 60 * 60 * 60 * 1000 //ms?? *1000? ? ???? 2592000000


